# Generated by Django 4.2.3 on 2023-08-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image_blog_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='comment',
            new_name='content',
        ),
    ]
