# Generated by Django 4.2.3 on 2023-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_date', '-blog_time']},
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
