# Generated by Django 4.2.3 on 2023-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_blog_blog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_time',
            field=models.TimeField(null=True),
        ),
    ]
