# Generated by Django 4.2.3 on 2023-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_order_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_datetime']},
        ),
        migrations.AddField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
