# Generated by Django 4.2.3 on 2023-09-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
    ]
